on:
  release:
    types:
      - released
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - id: lint
        run: echo "lint new release"
      - id: build
        run: echo "build new release"
  deploy-stage:
    runs-on: ubuntu-20.04
    needs: build
    environment: staging
    steps:
      - run: echo "deploy release"
  deploy-prod:
    runs-on: ubuntu-20.04
    needs: deploy-stage
    environment: production
    steps:
      - run: echo "deploy prod"
